### ISSUE TITLE
Create MailChimp template for promotional emails

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#15]

**Comment by Londonlime** [comment]
what’s it for, who is it for? which branding (nhs.ideas.lab?), have the content already (dummy content fine)? (when you have a moment to breathe!)

**Comment by DeckOfPandas** [comment]
We're going with Tinyletter emails for this event due to time, plus website
integration (which we also conveniently already know how to do).

I'll put login details in Slack.

I have content in the approval process already.

There will be several versions, with slightly different copy in each, but
the design will be the same so I will handle the copy.

**Comment by DeckOfPandas** [comment]
Closing as has been replaced by #35
