### ISSUE TITLE
Need for backup image in case background hero video doesn't play?

### ISSUE THREAD

**Issue by Londonlime** [DeckOfPandas/peanut-raspberry#19]
Let Ayesha know.

**Comment by Londonlime** [comment]
Uploading the two options for background image (if that's an option) for the video if it doesn't play. just a still from the video. will put here. no 1 is my favourite, but 2 should work too. I can't quite tell how it will interact with the other elements.

**Comment by DeckOfPandas** [comment]
These are in assets/img/basic/
video-background-still-1.jpg and video-background-still-2.jpg
@blu3id
