### ISSUE TITLE
Needs to be IE compatible

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#2]
Yep

**Comment by DeckOfPandas** [comment]
Apparently IE doesn't support position:sticky for navbar

**Comment by barneycarroll** [comment]
@DeckOfPandas what version range do you need to support? Just IE11 (+ Edge) 🤞?

**Comment by DeckOfPandas** [comment]
@barneycarroll Yes, thankfully that will be enough

**Comment by barneycarroll** [comment]
No IE-specific bugs that I can see anymore
