### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by Londonlime** [DeckOfPandas/peanut-raspberry#23]
Selection of square icons uploaded onto slack channel. Let me know if you need any other sizes or changes.

**Comment by DeckOfPandas** [comment]
Added to this repo

I'll close this Issue when I confirm I have the size I need :)

**Comment by DeckOfPandas** [comment]
Helen likes: 1, 2, 5, 10, 11, with slight preference for 5
Claire from BI likes: 1, 2, 10, 11

This is for twitter and facebook and linked in, then maybe favicon too, unless the one we like wouldn’t work for that

**Comment by Londonlime** [comment]
All the files are exported are ready for use as social media icons (advise if you need different sizes but I imagine they should do). 

I'll export all named options in .ico format so you can try them out as favicons.

**Comment by DeckOfPandas** [comment]
Perfect, thank you

**Comment by DeckOfPandas** [comment]
All done -- hurrah!
