### ISSUE TITLE
Explain difference between blocking/blocked to Ayesha :)

### ISSUE THREAD

**Issue by Londonlime** [DeckOfPandas/peanut-raspberry#29]

**Comment by DeckOfPandas** [comment]
Ha

'Blocking' is when some task is preventing another one from being completed, e.g. choosing a main logo is blocking email template design. So in that example the email template task is 'Blocked'.

If that is clunky I'll just drop those labels -- it's only my personal automatic way of working, and I don't really mind.

**Comment by Londonlime** [comment]
thanks! that makes sense. sounds good.
