### ISSUE TITLE
Switch for video with proper colours

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#3]

**Comment by Londonlime** [comment]
so looking at exporting in premiere, it seems to mess up the aspect if I change to quicktime export. I'll play some more but perhaps put that into play for now.

**Comment by DeckOfPandas** [comment]
Unfortunately the .mp4 you uploaded doesn't play :(

**Comment by DeckOfPandas** [comment]
Wait, yes it does. Closing this for now!

**Comment by Londonlime** [comment]
hmm. forgot to check the size, it's 8M bigger than the original version. I'll try and make that better.
