### ISSUE TITLE
BI and NHS England logos for footer (and possibly email)

### ISSUE THREAD

**Issue by Londonlime** [DeckOfPandas/peanut-raspberry#30]
The logos we have aren't quite suitable.

Website footer is dark, so we will need
a) a white version of the BI logo (this will need to be supplied/okayed by them. 
b) a vector version of the NHS England logo which is good for a dark background.

If we can't get these, we will change the colour of the footer (website and email) Your call if that seems like the easier thing to do!

**Comment by DeckOfPandas** [comment]
I have asked. Fingers crossed.

Do the email footer and website footer need to be the same color?

**Comment by Londonlime** [comment]
nope. they don't need to be the same colour.

**Comment by DeckOfPandas** [comment]
BI logo zip files uploaded to slack

**Comment by Londonlime** [comment]
BI logo in white transparent png uploaded to slack for the footer. Hopefully it can just shove everything else along (we might need the logos to be on a different line when NHS England turns up though)

**Comment by DeckOfPandas** [comment]
Someone is apparently sending me the NHS England media pack, so we should
be able to find whatever you think is best :)

**Comment by DeckOfPandas** [comment]
Footer made, just need to drop in correct logo now, so I'm downgrading the urgency!

**Comment by Londonlime** [comment]
last remaining logo uploaded here!

**Comment by DeckOfPandas** [comment]
Done
