### ISSUE TITLE
Design tinyletter email

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#35]
Including adding logo etc

**Comment by Londonlime** [comment]
Just flagging up that I've not used tinyletter before. Does it have responsive templates? I find emails even more of a x-compatible minefield than websites (used to be... think they are so much better now). as so many possible platforms,  devices and apps so not sure how much help I will be with tinyletter but happy to have a go! (with a good template it should be easier I imagine)

**Comment by Londonlime** [comment]
Subscribe page customised, in a limited yet homely way! 
Also put a logo image into the draft email you have there. (and it's uploaded into the file manager so you can use in future. let me know if I can do anymore.

**Comment by DeckOfPandas** [comment]
Just had a look, and it's great -- you've saved me so much time messing around with it too. THANK YOU!!!!
