### ISSUE TITLE
Posters/Flyers

### ISSUE THREAD

**Issue by Londonlime** [DeckOfPandas/peanut-raspberry#38]
Let me know when you have content (even dummy content) and I can start on these.

**Comment by DeckOfPandas** [comment]
Thanks! I'm just waiting to get the promotional emails and tweets etc
provisionally approved, then I will attempt to make you text content from
pre-approved words!

This will be after online launch, so after next Monday.

**Comment by Londonlime** [comment]
Ace. thanks!

**Comment by DeckOfPandas** [comment]
So we're a Go with this part of the project now!

How is best to work on this @Londonlime ? Me to produce text, or you to take words from the website, or something like you tell me where you want text and how much then I generate some!?

**Comment by Londonlime** [comment]
Love the idea of being asked how much text I want on it! usually people try and put an entire essay. 
I'd say you need to produce the text (as it could have a slightly different slant than text on a website (where people have already expressed interest by visiting). 
It would be great to just have exactly what you need (to get them to visit the website/ be interested enough) and no more :) But I can cope with whatever text you give me. Hope that's helpful!

**Comment by Londonlime** [comment]
A4/A3 posters?

**Comment by DeckOfPandas** [comment]
I've split these out into separate issues in the end...

**Comment by Londonlime** [comment]
so separate A3 and A4 posters? 
(flyers A6 or A5)

**Comment by DeckOfPandas** [comment]
Closing this as have split into other threads

Copy will follow tomorrow if we ever get this website out!
