### ISSUE TITLE
Suggestion for redoing {nhs.ideas.lab}

### ISSUE THREAD

**Issue by Londonlime** [DeckOfPandas/peanut-raspberry#39]
if you like it. I just thought the balance was a bit better (the thick orange is a bit shouty) and the widths are similiar
(this is without altering the base height which I don't know how to do in CSS (to make the brackets higher)
<img width="457" alt="screen shot 2017-10-18 at 10 19 07" src="https://user-images.githubusercontent.com/2213771/31712023-d355d91e-b3f1-11e7-8c51-af1f794c6051.png">
<img width="155" alt="screen shot 2017-10-18 at 10 18 54" src="https://user-images.githubusercontent.com/2213771/31712025-d36ee80a-b3f1-11e7-8e4f-0a1866b25945.png">
<img width="172" alt="screen shot 2017-10-18 at 10 18 29" src="https://user-images.githubusercontent.com/2213771/31712026-d3a47042-b3f1-11e7-99b1-a374cb5f0b3a.png">

**Comment by DeckOfPandas** [comment]
Looks good to me
This rather than the e.g. light logo you made @Londonlime ?

**Comment by Londonlime** [comment]
don't mind other options! we were thinking two logos would be too much, but perhaps the bulb graphic. not sure. might have to see it! but at least for now (so you can get on!) those changes might be easier.

**Comment by DeckOfPandas** [comment]
Going to abandon like this: 
![screen shot 2017-10-18 at 14 35 15](https://user-images.githubusercontent.com/2399432/31721567-993c1822-b411-11e7-8aff-778e4c21760e.png)
