### ISSUE TITLE
Navbar menu responsiveness is weird

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#40]
Second line in menu appears at 1199px
![screen shot 2017-10-18 at 11 47 51](https://user-images.githubusercontent.com/2399432/31715075-50df3332-b3fa-11e7-8fbc-5d8661486874.png)

Entire menu disappears at 1045px
![screen shot 2017-10-18 at 11 48 02](https://user-images.githubusercontent.com/2399432/31715082-58795064-b3fa-11e7-8d5e-48b88c75c627.png)

Button menu appears at 1023 px
![screen shot 2017-10-18 at 11 48 10](https://user-images.githubusercontent.com/2399432/31715083-5a6fa7d8-b3fa-11e7-9979-24258f09a193.png)

**Comment by Londonlime** [comment]
and this is my screen. basically the deeper menu bar is obscuring the next section (at about 1180px wide) 
<img width="1082" alt="screen shot 2017-10-18 at 11 51 07" src="https://user-images.githubusercontent.com/2213771/31715225-d5ced8ae-b3fa-11e7-9190-dfb9fc1f88a9.png">
(was an 'in action' shot hence the typewriter bit being over to the right somewhat)
