### ISSUE TITLE
Add our logo to header and footer

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#6]

**Comment by Londonlime** [comment]
transparent png logo for dark background website 265px wide (so the top menu bar will need to be deeper, but it will probably just automatically stretch when you wack this in. 
in slack channel NHSIdeasLabLogo-website.png

**Comment by Londonlime** [comment]
(not sure whether to take off blocked or blocking as not clear on difference!)

**Comment by DeckOfPandas** [comment]
Done
