### ISSUE TITLE
Navbar menu is collapsed in 'print preview' mode

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#62]
![screen shot 2017-10-23 at 10 07 05](https://user-images.githubusercontent.com/2399432/31880946-f6ae3230-b7d9-11e7-88db-542f567c8c5b.png)

**Comment by barneycarroll** [comment]
The critical parts of this (both desktop & mobile menus showing at the same time) is subsumed into #98.
