### ISSUE TITLE
Agree favicon

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#7]

**Comment by Londonlime** [comment]
social media icons 400.zip on the slack channel

Every variation under the sun (nearly) :slightly_smiling_face: exported as 400px square pngs. Let me know if you'd want any particular one converted to a favicon to try out. (not sure of the modern process.. used to be the .ico format?)

**Comment by DeckOfPandas** [comment]
It seems that the favicon in my template pack was a .ico

I guess we now 'just' need to agree on which of your gorgeous options to use!

**Comment by Londonlime** [comment]
chosen options converted to .ico and uploaded here. (still can't work out how to do a folder!)

**Comment by DeckOfPandas** [comment]
Thanks :)

Maybe folders aren't possible?!

**Comment by DeckOfPandas** [comment]
Done! :)
