### ISSUE TITLE
Typewriter still not reliably appearing 

### ISSUE THREAD

**Issue by davidmiller** [DeckOfPandas/peanut-raspberry#83]
e.g. second visit etc: 

![screen shot 2017-10-24 at 07 56 11](https://user-images.githubusercontent.com/17229/31928673-e752d478-b890-11e7-854e-b4e87c1f1eee.png)
(On live site...)

**Comment by davidmiller** [comment]
Hard to debug this in a browser because the compiled JS is compiled.... Propose reverting to text until it can be made to behave?

**Comment by DeckOfPandas** [comment]
Actually even with the static text fix in #84 the title doesn't display reliably on refresh...

**Comment by DeckOfPandas** [comment]
@barneycarroll Ideally we'd go back to the annoying but "innovation"-looking typewriter text
